
services:
  prospectio-chatbot:
    build:
      context: ./prospectio-chatbot
      dockerfile: Dockerfile
    container_name: prospectio-chatbot
    ports:
      - "8000:8000"
    networks:
      - prospectio
    env_file:
      - .env.docker
    depends_on:
      prospectio-chatbot-db:
        condition: service_healthy
  prospectio-chatbot-db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: prospectio-chatbot-pgvector
    environment:
      POSTGRES_USER: prospectio
      POSTGRES_PASSWORD: prospectio
      POSTGRES_DB: prospectio
    ports:
      - "5434:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prospectio -d prospectio"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prospectio

networks:
  prospectio:
    external: true